19-Apr-2023 23:15:02.116 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
19-Apr-2023 23:15:02.120 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
19-Apr-2023 23:15:02.125 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@6b886e86')
19-Apr-2023 23:26:57.654 SEVERE [http-nio-8080-exec-5] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:27:34.603 SEVERE [http-nio-8080-exec-7] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:27:58.983 SEVERE [http-nio-8080-exec-10] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:28:35.914 SEVERE [http-nio-8080-exec-6] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:29:16.939 SEVERE [http-nio-8080-exec-10] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:35:53.726 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
19-Apr-2023 23:35:53.732 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
19-Apr-2023 23:35:53.743 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@68a06914')
19-Apr-2023 23:42:09.391 SEVERE [http-nio-8080-exec-1] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:42:28.563 SEVERE [http-nio-8080-exec-5] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:42:40.285 SEVERE [http-nio-8080-exec-9] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:46:27.624 SEVERE [http-nio-8080-exec-10] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:48:16.585 SEVERE [http-nio-8080-exec-2] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:48:25.460 SEVERE [http-nio-8080-exec-4] org.apache.catalina.realm.DataSourceRealm.open Exception performing authentication
	java.sql.SQLException: Cannot create PoolableConnectionFactory (FATAL: password authentication failed for user "postgres")
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:632)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:534)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:710)
		at org.apache.catalina.realm.DataSourceRealm.open(DataSourceRealm.java:376)
		at org.apache.catalina.realm.DataSourceRealm.authenticate(DataSourceRealm.java:249)
		at org.apache.catalina.realm.CombinedRealm.authenticate(CombinedRealm.java:172)
		at org.apache.catalina.realm.LockOutRealm.authenticate(LockOutRealm.java:141)
		at org.apache.catalina.authenticator.FormAuthenticator.doAuthenticate(FormAuthenticator.java:238)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:574)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:676)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:341)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.base/java.lang.Thread.run(Thread.java:1589)
	Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
		at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:693)
		at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
		at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
		at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
		at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:253)
		at org.postgresql.Driver.makeConnection(Driver.java:434)
		at org.postgresql.Driver.connect(Driver.java:291)
		at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:52)
		at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:414)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:112)
		at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:628)
		... 22 more
19-Apr-2023 23:51:25.423 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: contextInitialized()
19-Apr-2023 23:51:25.425 INFO [main] org.apache.catalina.core.ApplicationContext.log SessionListener: contextInitialized()
19-Apr-2023 23:51:25.432 INFO [main] org.apache.catalina.core.ApplicationContext.log ContextListener: attributeAdded('StockTicker', 'async.Stockticker@ebd4486')
